language: go
script:  ./scripts/run-tests.sh
sudo: false
go:
  - 1.6
  - tip
matrix:
  allow_failures:
    - go: tip
notifications:
    on_success: "change"  # options: [always|never|change] default: always
    on_failure: "always"  # options: [always|never|change] default: always
    on_start: false     # default: false